def dark_sky_weather_response
  ActiveSupport::HashWithIndifferentAccess.new({
    "latitude": 43.64888,
    "longitude": -72.319588,
    "timezone": "America/New_York",
    "currently": {
        "time": 1578849058,
        "summary": "Mostly Cloudy",
        "icon": "partly-cloudy-day",
        "nearestStormDistance": 21,
        "nearestStormBearing": 285,
        "precipIntensity": 0,
        "precipProbability": 0,
        "temperature": 54.96,
        "apparentTemperature": 55.05,
        "dewPoint": 41.55,
        "humidity": 0.6,
        "pressure": 1010.5,
        "windSpeed": 12.96,
        "windGust": 22.54,
        "windBearing": 320,
        "cloudCover": 0.6,
        "uvIndex": 1,
        "visibility": 10,
        "ozone": 305.4
    },
    "minutely": {
        "summary": "Mostly cloudy for the hour.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1578849000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849600,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849660,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849720,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849780,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849840,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849900,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578849960,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850020,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850080,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850140,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850200,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850260,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850320,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850380,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850440,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850500,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850560,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850620,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850680,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850740,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850800,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850860,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850920,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578850980,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851040,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851100,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851160,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851220,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851280,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851340,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851400,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851460,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851520,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851580,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851640,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851700,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851760,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851820,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851880,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578851940,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852000,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852060,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852120,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852180,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852240,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852300,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852360,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852420,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852480,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852540,
                "precipIntensity": 0,
                "precipProbability": 0
            },
            {
                "time": 1578852600,
                "precipIntensity": 0,
                "precipProbability": 0
            }
        ]
    },
    "hourly": {
        "summary": "Mostly cloudy throughout the day.",
        "icon": "partly-cloudy-day",
        "data": [
            {
                "time": 1578848400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0007,
                "precipProbability": 0.19,
                "precipType": "rain",
                "temperature": 55.67,
                "apparentTemperature": 55.67,
                "dewPoint": 42.49,
                "humidity": 0.61,
                "pressure": 1010.1,
                "windSpeed": 12.93,
                "windGust": 22.71,
                "windBearing": 320,
                "cloudCover": 0.62,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 305.7
            },
            {
                "time": 1578852000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 51.77,
                "apparentTemperature": 51.77,
                "dewPoint": 37.95,
                "humidity": 0.59,
                "pressure": 1012.7,
                "windSpeed": 12.7,
                "windGust": 21.26,
                "windBearing": 300,
                "cloudCover": 0.57,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 303.7
            },
            {
                "time": 1578855600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0013,
                "precipProbability": 0.06,
                "precipType": "rain",
                "temperature": 46.1,
                "apparentTemperature": 40.04,
                "dewPoint": 33.98,
                "humidity": 0.62,
                "pressure": 1015.6,
                "windSpeed": 13.57,
                "windGust": 28.96,
                "windBearing": 258,
                "cloudCover": 0.47,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 301.3
            },
            {
                "time": 1578859200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 40.36,
                "apparentTemperature": 33.12,
                "dewPoint": 32.78,
                "humidity": 0.74,
                "pressure": 1018.5,
                "windSpeed": 12.47,
                "windGust": 28.74,
                "windBearing": 335,
                "cloudCover": 0.39,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 298.4
            },
            {
                "time": 1578862800,
                "summary": "Clear",
                "icon": "clear-day",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 35.84,
                "apparentTemperature": 27.72,
                "dewPoint": 28.31,
                "humidity": 0.74,
                "pressure": 1020.8,
                "windSpeed": 11.74,
                "windGust": 24.76,
                "windBearing": 320,
                "cloudCover": 0.3,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 296.5
            },
            {
                "time": 1578866400,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 31.49,
                "apparentTemperature": 22.49,
                "dewPoint": 23.7,
                "humidity": 0.73,
                "pressure": 1023.2,
                "windSpeed": 11.22,
                "windGust": 23.36,
                "windBearing": 321,
                "cloudCover": 0.34,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 296.3
            },
            {
                "time": 1578870000,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 28.08,
                "apparentTemperature": 18.24,
                "dewPoint": 20.05,
                "humidity": 0.72,
                "pressure": 1025.1,
                "windSpeed": 11.18,
                "windGust": 23.57,
                "windBearing": 328,
                "cloudCover": 0.42,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 297.1
            },
            {
                "time": 1578873600,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.002,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0197,
                "temperature": 25.29,
                "apparentTemperature": 14.89,
                "dewPoint": 18.11,
                "humidity": 0.74,
                "pressure": 1027.3,
                "windSpeed": 10.94,
                "windGust": 22.99,
                "windBearing": 338,
                "cloudCover": 0.49,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 298.2
            },
            {
                "time": 1578877200,
                "summary": "Partly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 23.44,
                "apparentTemperature": 13.14,
                "dewPoint": 17.17,
                "humidity": 0.77,
                "pressure": 1028.5,
                "windSpeed": 9.96,
                "windGust": 21.74,
                "windBearing": 344,
                "cloudCover": 0.49,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.8
            },
            {
                "time": 1578880800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0021,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0249,
                "temperature": 21.98,
                "apparentTemperature": 12.15,
                "dewPoint": 16.14,
                "humidity": 0.78,
                "pressure": 1029.8,
                "windSpeed": 8.69,
                "windGust": 19.69,
                "windBearing": 352,
                "cloudCover": 0.78,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 301.8
            },
            {
                "time": 1578884400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 21.09,
                "apparentTemperature": 12.24,
                "dewPoint": 15.48,
                "humidity": 0.79,
                "pressure": 1030.8,
                "windSpeed": 7.13,
                "windGust": 16.38,
                "windBearing": 358,
                "cloudCover": 0.86,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.7
            },
            {
                "time": 1578888000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 20.45,
                "apparentTemperature": 12.44,
                "dewPoint": 15.12,
                "humidity": 0.79,
                "pressure": 1031.7,
                "windSpeed": 6.04,
                "windGust": 13.33,
                "windBearing": 1,
                "cloudCover": 0.85,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 301.9
            },
            {
                "time": 1578891600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 19.99,
                "apparentTemperature": 13.12,
                "dewPoint": 14.87,
                "humidity": 0.8,
                "pressure": 1031.7,
                "windSpeed": 4.86,
                "windGust": 9.86,
                "windBearing": 5,
                "cloudCover": 0.84,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 300.2
            },
            {
                "time": 1578895200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.3,
                "apparentTemperature": 11.99,
                "dewPoint": 12.52,
                "humidity": 0.81,
                "pressure": 1033.3,
                "windSpeed": 3.41,
                "windGust": 5.97,
                "windBearing": 13,
                "cloudCover": 0.74,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.1
            },
            {
                "time": 1578898800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.15,
                "apparentTemperature": 17.15,
                "dewPoint": 12.56,
                "humidity": 0.82,
                "pressure": 1033.7,
                "windSpeed": 2.59,
                "windGust": 4.12,
                "windBearing": 28,
                "cloudCover": 0.73,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.1
            },
            {
                "time": 1578902400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.21,
                "apparentTemperature": 17.21,
                "dewPoint": 12.82,
                "humidity": 0.83,
                "pressure": 1034.2,
                "windSpeed": 1.92,
                "windGust": 2.82,
                "windBearing": 47,
                "cloudCover": 0.73,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 299.6
            },
            {
                "time": 1578906000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.33,
                "apparentTemperature": 17.33,
                "dewPoint": 13.16,
                "humidity": 0.83,
                "pressure": 1034.2,
                "windSpeed": 1.76,
                "windGust": 2.79,
                "windBearing": 67,
                "cloudCover": 0.75,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 300.6
            },
            {
                "time": 1578909600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.37,
                "apparentTemperature": 17.37,
                "dewPoint": 13.6,
                "humidity": 0.85,
                "pressure": 1034,
                "windSpeed": 2.33,
                "windGust": 4.77,
                "windBearing": 89,
                "cloudCover": 0.79,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 302.4
            },
            {
                "time": 1578913200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.17,
                "apparentTemperature": 11.82,
                "dewPoint": 14.1,
                "humidity": 0.87,
                "pressure": 1033.9,
                "windSpeed": 3.42,
                "windGust": 8.04,
                "windBearing": 114,
                "cloudCover": 0.84,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 304.8
            },
            {
                "time": 1578916800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 17.49,
                "apparentTemperature": 10.51,
                "dewPoint": 14.86,
                "humidity": 0.89,
                "pressure": 1033.5,
                "windSpeed": 4.6,
                "windGust": 11.1,
                "windBearing": 133,
                "cloudCover": 0.87,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 306.7
            },
            {
                "time": 1578920400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0039,
                "temperature": 18.73,
                "apparentTemperature": 10.36,
                "dewPoint": 15.39,
                "humidity": 0.87,
                "pressure": 1033.4,
                "windSpeed": 6.07,
                "windGust": 13.7,
                "windBearing": 141,
                "cloudCover": 0.85,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 307.5
            },
            {
                "time": 1578924000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0026,
                "temperature": 20.77,
                "apparentTemperature": 11.46,
                "dewPoint": 16.62,
                "humidity": 0.84,
                "pressure": 1033.4,
                "windSpeed": 7.63,
                "windGust": 16.07,
                "windBearing": 142,
                "cloudCover": 0.8,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 307.8
            },
            {
                "time": 1578927600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0024,
                "temperature": 22.57,
                "apparentTemperature": 12.96,
                "dewPoint": 18.06,
                "humidity": 0.83,
                "pressure": 1033,
                "windSpeed": 8.56,
                "windGust": 17.43,
                "windBearing": 144,
                "cloudCover": 0.76,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 308.5
            },
            {
                "time": 1578931200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0033,
                "temperature": 24.65,
                "apparentTemperature": 15.61,
                "dewPoint": 19.29,
                "humidity": 0.8,
                "pressure": 1032.3,
                "windSpeed": 8.41,
                "windGust": 17.28,
                "windBearing": 146,
                "cloudCover": 0.76,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 310
            },
            {
                "time": 1578934800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0006,
                "precipProbability": 0.03,
                "precipType": "snow",
                "precipAccumulation": 0.0056,
                "temperature": 26.92,
                "apparentTemperature": 18.91,
                "dewPoint": 20.64,
                "humidity": 0.77,
                "pressure": 1031.3,
                "windSpeed": 7.64,
                "windGust": 16.18,
                "windBearing": 148,
                "cloudCover": 0.77,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 311.9
            },
            {
                "time": 1578938400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.001,
                "precipProbability": 0.04,
                "precipType": "snow",
                "precipAccumulation": 0.0066,
                "temperature": 29.09,
                "apparentTemperature": 22.11,
                "dewPoint": 21.74,
                "humidity": 0.74,
                "pressure": 1030.5,
                "windSpeed": 6.83,
                "windGust": 14.97,
                "windBearing": 150,
                "cloudCover": 0.8,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 313.8
            },
            {
                "time": 1578942000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-day",
                "precipIntensity": 0.0009,
                "precipProbability": 0.04,
                "precipType": "snow",
                "precipAccumulation": 0.0047,
                "temperature": 30.81,
                "apparentTemperature": 24.66,
                "dewPoint": 22.9,
                "humidity": 0.72,
                "pressure": 1029.9,
                "windSpeed": 6.2,
                "windGust": 14.03,
                "windBearing": 151,
                "cloudCover": 0.86,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 315.8
            },
            {
                "time": 1578945600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0006,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 31.85,
                "apparentTemperature": 26.42,
                "dewPoint": 23.95,
                "humidity": 0.72,
                "pressure": 1029.4,
                "windSpeed": 5.54,
                "windGust": 12.97,
                "windBearing": 151,
                "cloudCover": 0.94,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 317.9
            },
            {
                "time": 1578949200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0005,
                "precipProbability": 0.03,
                "precipType": "rain",
                "temperature": 32.13,
                "apparentTemperature": 27.32,
                "dewPoint": 25,
                "humidity": 0.75,
                "pressure": 1029.1,
                "windSpeed": 4.9,
                "windGust": 11.53,
                "windBearing": 152,
                "cloudCover": 1,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 320.2
            },
            {
                "time": 1578952800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0006,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 31.14,
                "apparentTemperature": 26.82,
                "dewPoint": 25.16,
                "humidity": 0.78,
                "pressure": 1029.1,
                "windSpeed": 4.24,
                "windGust": 9.24,
                "windBearing": 152,
                "cloudCover": 0.99,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 323.1
            },
            {
                "time": 1578956400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.001,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0062,
                "temperature": 29.66,
                "apparentTemperature": 25.87,
                "dewPoint": 25.71,
                "humidity": 0.85,
                "pressure": 1029.4,
                "windSpeed": 3.59,
                "windGust": 6.44,
                "windBearing": 151,
                "cloudCover": 0.98,
                "uvIndex": 0,
                "visibility": 9.936,
                "ozone": 326.2
            },
            {
                "time": 1578960000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0012,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0091,
                "temperature": 28.72,
                "apparentTemperature": 25.5,
                "dewPoint": 26.24,
                "humidity": 0.9,
                "pressure": 1029.6,
                "windSpeed": 3.07,
                "windGust": 4.3,
                "windBearing": 152,
                "cloudCover": 0.96,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 328.6
            },
            {
                "time": 1578963600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0008,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0063,
                "temperature": 28.33,
                "apparentTemperature": 28.33,
                "dewPoint": 26.17,
                "humidity": 0.92,
                "pressure": 1029.4,
                "windSpeed": 2.82,
                "windGust": 3.7,
                "windBearing": 162,
                "cloudCover": 0.95,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 330.2
            },
            {
                "time": 1578967200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0003,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0027,
                "temperature": 28.05,
                "apparentTemperature": 28.05,
                "dewPoint": 26.18,
                "humidity": 0.93,
                "pressure": 1029.2,
                "windSpeed": 2.73,
                "windGust": 3.89,
                "windBearing": 176,
                "cloudCover": 0.93,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 331.1
            },
            {
                "time": 1578970800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0002,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0016,
                "temperature": 27.71,
                "apparentTemperature": 27.71,
                "dewPoint": 26.39,
                "humidity": 0.95,
                "pressure": 1029.1,
                "windSpeed": 2.61,
                "windGust": 3.92,
                "windBearing": 186,
                "cloudCover": 0.91,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 331.7
            },
            {
                "time": 1578974400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.58,
                "apparentTemperature": 27.58,
                "dewPoint": 26.81,
                "humidity": 0.97,
                "pressure": 1028.9,
                "windSpeed": 2.36,
                "windGust": 3.32,
                "windBearing": 191,
                "cloudCover": 0.88,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 332.1
            },
            {
                "time": 1578978000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.52,
                "apparentTemperature": 27.52,
                "dewPoint": 27.27,
                "humidity": 0.99,
                "pressure": 1028.7,
                "windSpeed": 2.08,
                "windGust": 2.56,
                "windBearing": 285,
                "cloudCover": 0.84,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 332.1
            },
            {
                "time": 1578981600,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.6,
                "apparentTemperature": 27.6,
                "dewPoint": 27.6,
                "humidity": 1,
                "pressure": 1028.6,
                "windSpeed": 1.89,
                "windGust": 2.07,
                "windBearing": 267,
                "cloudCover": 0.82,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 332.2
            },
            {
                "time": 1578985200,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.87,
                "apparentTemperature": 27.87,
                "dewPoint": 27.87,
                "humidity": 1,
                "pressure": 1028.3,
                "windSpeed": 1.83,
                "windGust": 2,
                "windBearing": 161,
                "cloudCover": 0.83,
                "uvIndex": 0,
                "visibility": 10,
                "ozone": 332.4
            },
            {
                "time": 1578988800,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0004,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0031,
                "temperature": 28.1,
                "apparentTemperature": 28.1,
                "dewPoint": 28.1,
                "humidity": 1,
                "pressure": 1028,
                "windSpeed": 1.81,
                "windGust": 2.11,
                "windBearing": 306,
                "cloudCover": 0.85,
                "uvIndex": 0,
                "visibility": 9.942,
                "ozone": 332.6
            },
            {
                "time": 1578992400,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0005,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0043,
                "temperature": 28.18,
                "apparentTemperature": 28.18,
                "dewPoint": 28.18,
                "humidity": 1,
                "pressure": 1028,
                "windSpeed": 1.83,
                "windGust": 2.24,
                "windBearing": 294,
                "cloudCover": 0.87,
                "uvIndex": 0,
                "visibility": 7.535,
                "ozone": 332.9
            },
            {
                "time": 1578996000,
                "summary": "Mostly Cloudy",
                "icon": "partly-cloudy-night",
                "precipIntensity": 0.0003,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.0028,
                "temperature": 27.86,
                "apparentTemperature": 27.86,
                "dewPoint": 27.86,
                "humidity": 1,
                "pressure": 1028.1,
                "windSpeed": 1.88,
                "windGust": 2.27,
                "windBearing": 308,
                "cloudCover": 0.87,
                "uvIndex": 0,
                "visibility": 6.854,
                "ozone": 332.8
            },
            {
                "time": 1578999600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.47,
                "apparentTemperature": 27.47,
                "dewPoint": 27.47,
                "humidity": 1,
                "pressure": 1028.4,
                "windSpeed": 1.97,
                "windGust": 2.3,
                "windBearing": 352,
                "cloudCover": 0.88,
                "uvIndex": 0,
                "visibility": 6.137,
                "ozone": 332.7
            },
            {
                "time": 1579003200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.24,
                "apparentTemperature": 27.24,
                "dewPoint": 27.24,
                "humidity": 1,
                "pressure": 1028.6,
                "windSpeed": 2.06,
                "windGust": 2.48,
                "windBearing": 238,
                "cloudCover": 0.9,
                "uvIndex": 0,
                "visibility": 5.784,
                "ozone": 333.6
            },
            {
                "time": 1579006800,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 27.62,
                "apparentTemperature": 27.62,
                "dewPoint": 27.62,
                "humidity": 1,
                "pressure": 1028.3,
                "windSpeed": 2.01,
                "windGust": 2.54,
                "windBearing": 208,
                "cloudCover": 0.91,
                "uvIndex": 0,
                "visibility": 6.237,
                "ozone": 336.4
            },
            {
                "time": 1579010400,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0003,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0018,
                "temperature": 28.68,
                "apparentTemperature": 28.68,
                "dewPoint": 28.68,
                "humidity": 1,
                "pressure": 1027.7,
                "windSpeed": 1.97,
                "windGust": 2.68,
                "windBearing": 131,
                "cloudCover": 0.93,
                "uvIndex": 0,
                "visibility": 7.143,
                "ozone": 340.1
            },
            {
                "time": 1579014000,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0005,
                "precipProbability": 0.01,
                "precipType": "snow",
                "precipAccumulation": 0.0025,
                "temperature": 30.13,
                "apparentTemperature": 30.13,
                "dewPoint": 29.83,
                "humidity": 0.99,
                "pressure": 1027.1,
                "windSpeed": 2.2,
                "windGust": 3.43,
                "windBearing": 114,
                "cloudCover": 0.93,
                "uvIndex": 1,
                "visibility": 8.06,
                "ozone": 343.2
            },
            {
                "time": 1579017600,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0.0003,
                "precipProbability": 0.02,
                "precipType": "rain",
                "temperature": 32.91,
                "apparentTemperature": 32.91,
                "dewPoint": 30.08,
                "humidity": 0.89,
                "pressure": 1026.2,
                "windSpeed": 2.98,
                "windGust": 5.36,
                "windBearing": 126,
                "cloudCover": 0.93,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 344.9
            },
            {
                "time": 1579021200,
                "summary": "Overcast",
                "icon": "cloudy",
                "precipIntensity": 0,
                "precipProbability": 0,
                "temperature": 36.27,
                "apparentTemperature": 32.94,
                "dewPoint": 30.75,
                "humidity": 0.8,
                "pressure": 1025.2,
                "windSpeed": 4.08,
                "windGust": 7.96,
                "windBearing": 145,
                "cloudCover": 0.91,
                "uvIndex": 1,
                "visibility": 10,
                "ozone": 345.8
            }
        ]
    },
    "daily": {
        "summary": "Mixed precipitation throughout the week.",
        "icon": "sleet",
        "data": [
            {
                "time": 1578805200,
                "summary": "Light rain in the morning.",
                "icon": "rain",
                "sunriseTime": 1578831720,
                "sunsetTime": 1578864900,
                "moonPhase": 0.58,
                "precipIntensity": 0.0077,
                "precipIntensityMax": 0.0632,
                "precipIntensityMaxTime": 1578823440,
                "precipProbability": 0.98,
                "precipType": "rain",
                "temperatureHigh": 60.38,
                "temperatureHighTime": 1578844380,
                "temperatureLow": 16.56,
                "temperatureLowTime": 1578896700,
                "apparentTemperatureHigh": 59.88,
                "apparentTemperatureHighTime": 1578844380,
                "apparentTemperatureLow": 10.27,
                "apparentTemperatureLowTime": 1578919080,
                "dewPoint": 37.98,
                "humidity": 0.81,
                "pressure": 1015.1,
                "windSpeed": 8.24,
                "windGust": 29.63,
                "windGustTime": 1578856980,
                "windBearing": 305,
                "cloudCover": 0.73,
                "uvIndex": 1,
                "uvIndexTime": 1578848580,
                "visibility": 9.436,
                "ozone": 298.1,
                "temperatureMin": 19.5,
                "temperatureMinTime": 1578891600,
                "temperatureMax": 60.38,
                "temperatureMaxTime": 1578844380,
                "apparentTemperatureMin": 12.09,
                "apparentTemperatureMinTime": 1578881820,
                "apparentTemperatureMax": 59.88,
                "apparentTemperatureMaxTime": 1578844380
            },
            {
                "time": 1578891600,
                "summary": "Mostly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1578918120,
                "sunsetTime": 1578951360,
                "moonPhase": 0.62,
                "precipIntensity": 0.0004,
                "precipIntensityMax": 0.0012,
                "precipIntensityMaxTime": 1578959640,
                "precipProbability": 0.08,
                "precipType": "snow",
                "precipAccumulation": 0.08,
                "temperatureHigh": 32.67,
                "temperatureHighTime": 1578948420,
                "temperatureLow": 26.75,
                "temperatureLowTime": 1579002960,
                "apparentTemperatureHigh": 27.32,
                "apparentTemperatureHighTime": 1578949500,
                "apparentTemperatureLow": 25.5,
                "apparentTemperatureLowTime": 1578960000,
                "dewPoint": 20.03,
                "humidity": 0.84,
                "pressure": 1031.4,
                "windSpeed": 4.44,
                "windGust": 17.53,
                "windGustTime": 1578928800,
                "windBearing": 141,
                "cloudCover": 0.85,
                "uvIndex": 1,
                "uvIndexTime": 1578934560,
                "visibility": 9.998,
                "ozone": 314.4,
                "temperatureMin": 16.56,
                "temperatureMinTime": 1578896700,
                "temperatureMax": 32.67,
                "temperatureMaxTime": 1578948420,
                "apparentTemperatureMin": 10.27,
                "apparentTemperatureMinTime": 1578919080,
                "apparentTemperatureMax": 28.48,
                "apparentTemperatureMaxTime": 1578964500
            },
            {
                "time": 1578978000,
                "summary": "Foggy in the evening and overnight.",
                "icon": "fog",
                "sunriseTime": 1579004460,
                "sunsetTime": 1579037820,
                "moonPhase": 0.66,
                "precipIntensity": 0.0021,
                "precipIntensityMax": 0.0071,
                "precipIntensityMaxTime": 1579045980,
                "precipProbability": 0.28,
                "precipType": "rain",
                "temperatureHigh": 38.98,
                "temperatureHighTime": 1579025880,
                "temperatureLow": 33.43,
                "temperatureLowTime": 1579057140,
                "apparentTemperatureHigh": 34.53,
                "apparentTemperatureHighTime": 1579025220,
                "apparentTemperatureLow": 27.97,
                "apparentTemperatureLowTime": 1579056660,
                "dewPoint": 29.91,
                "humidity": 0.92,
                "pressure": 1024.1,
                "windSpeed": 4.25,
                "windGust": 19.92,
                "windGustTime": 1579048440,
                "windBearing": 156,
                "cloudCover": 0.93,
                "uvIndex": 1,
                "uvIndexTime": 1579021080,
                "visibility": 6.647,
                "ozone": 344.4,
                "temperatureMin": 26.75,
                "temperatureMinTime": 1579002960,
                "temperatureMax": 38.98,
                "temperatureMaxTime": 1579025880,
                "apparentTemperatureMin": 27.24,
                "apparentTemperatureMinTime": 1579002960,
                "apparentTemperatureMax": 34.53,
                "apparentTemperatureMaxTime": 1579025220
            },
            {
                "time": 1579064400,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1579090860,
                "sunsetTime": 1579124280,
                "moonPhase": 0.7,
                "precipIntensity": 0.0004,
                "precipIntensityMax": 0.0039,
                "precipIntensityMaxTime": 1579064400,
                "precipProbability": 0.18,
                "precipType": "rain",
                "temperatureHigh": 42.66,
                "temperatureHighTime": 1579111140,
                "temperatureLow": 27.92,
                "temperatureLowTime": 1579168500,
                "apparentTemperatureHigh": 36.29,
                "apparentTemperatureHighTime": 1579111560,
                "apparentTemperatureLow": 23.47,
                "apparentTemperatureLowTime": 1579179600,
                "dewPoint": 30.85,
                "humidity": 0.85,
                "pressure": 1015.2,
                "windSpeed": 6.29,
                "windGust": 23.66,
                "windGustTime": 1579091700,
                "windBearing": 267,
                "cloudCover": 0.56,
                "uvIndex": 1,
                "uvIndexTime": 1579107660,
                "visibility": 9.313,
                "ozone": 364.9,
                "temperatureMin": 28.92,
                "temperatureMinTime": 1579150800,
                "temperatureMax": 42.66,
                "temperatureMaxTime": 1579111140,
                "apparentTemperatureMin": 28.13,
                "apparentTemperatureMinTime": 1579130460,
                "apparentTemperatureMax": 36.29,
                "apparentTemperatureMaxTime": 1579111560
            },
            {
                "time": 1579150800,
                "summary": "Partly cloudy throughout the day.",
                "icon": "partly-cloudy-day",
                "sunriseTime": 1579177200,
                "sunsetTime": 1579210800,
                "moonPhase": 0.73,
                "precipIntensity": 0.0012,
                "precipIntensityMax": 0.0053,
                "precipIntensityMaxTime": 1579156560,
                "precipProbability": 0.2,
                "precipType": "snow",
                "precipAccumulation": 0.25,
                "temperatureHigh": 32.04,
                "temperatureHighTime": 1579192680,
                "temperatureLow": 9.62,
                "temperatureLowTime": 1579263840,
                "apparentTemperatureHigh": 23.87,
                "apparentTemperatureHighTime": 1579176000,
                "apparentTemperatureLow": -3.03,
                "apparentTemperatureLowTime": 1579264500,
                "dewPoint": 19.39,
                "humidity": 0.73,
                "pressure": 1021.2,
                "windSpeed": 8.15,
                "windGust": 28.51,
                "windGustTime": 1579207320,
                "windBearing": 317,
                "cloudCover": 0.7,
                "uvIndex": 1,
                "uvIndexTime": 1579193580,
                "visibility": 9.94,
                "ozone": 369,
                "temperatureMin": 16.41,
                "temperatureMinTime": 1579237200,
                "temperatureMax": 32.04,
                "temperatureMaxTime": 1579192680,
                "apparentTemperatureMin": 4.71,
                "apparentTemperatureMinTime": 1579237200,
                "apparentTemperatureMax": 29.41,
                "apparentTemperatureMaxTime": 1579150800
            },
            {
                "time": 1579237200,
                "summary": "Clear throughout the day.",
                "icon": "clear-day",
                "sunriseTime": 1579263600,
                "sunsetTime": 1579297260,
                "moonPhase": 0.77,
                "precipIntensity": 0.0001,
                "precipIntensityMax": 0.0003,
                "precipIntensityMaxTime": 1579262640,
                "precipProbability": 0.02,
                "precipType": "snow",
                "precipAccumulation": 0.03,
                "temperatureHigh": 16.32,
                "temperatureHighTime": 1579290300,
                "temperatureLow": 6.42,
                "temperatureLowTime": 1579316460,
                "apparentTemperatureHigh": 6.8,
                "apparentTemperatureHighTime": 1579293780,
                "apparentTemperatureLow": -1.14,
                "apparentTemperatureLowTime": 1579315260,
                "dewPoint": -3.73,
                "humidity": 0.49,
                "pressure": 1034.6,
                "windSpeed": 7.48,
                "windGust": 26.87,
                "windGustTime": 1579260060,
                "windBearing": 341,
                "cloudCover": 0.43,
                "uvIndex": 1,
                "uvIndexTime": 1579280520,
                "visibility": 10,
                "ozone": 354.6,
                "temperatureMin": 6.42,
                "temperatureMinTime": 1579316460,
                "temperatureMax": 17.4,
                "temperatureMaxTime": 1579237200,
                "apparentTemperatureMin": -3.03,
                "apparentTemperatureMinTime": 1579264500,
                "apparentTemperatureMax": 6.8,
                "apparentTemperatureMaxTime": 1579293780
            },
            {
                "time": 1579323600,
                "summary": "Light snow throughout the day.",
                "icon": "snow",
                "sunriseTime": 1579349940,
                "sunsetTime": 1579383720,
                "moonPhase": 0.8,
                "precipIntensity": 0.0333,
                "precipIntensityMax": 0.0588,
                "precipIntensityMaxTime": 1579400460,
                "precipProbability": 0.87,
                "precipType": "snow",
                "precipAccumulation": 11.36,
                "temperatureHigh": 25.01,
                "temperatureHighTime": 1579392000,
                "temperatureLow": 15.63,
                "temperatureLowTime": 1579438260,
                "apparentTemperatureHigh": 13.58,
                "apparentTemperatureHighTime": 1579370280,
                "apparentTemperatureLow": 2.11,
                "apparentTemperatureLowTime": 1579438800,
                "dewPoint": 11.57,
                "humidity": 0.72,
                "pressure": 1012.2,
                "windSpeed": 9.7,
                "windGust": 44.23,
                "windGustTime": 1579387920,
                "windBearing": 116,
                "cloudCover": 1,
                "uvIndex": 1,
                "uvIndexTime": 1579366800,
                "visibility": 2.716,
                "ozone": 347.2,
                "temperatureMin": 7.52,
                "temperatureMinTime": 1579323600,
                "temperatureMax": 26.78,
                "temperatureMaxTime": 1579401540,
                "apparentTemperatureMin": 0.67,
                "apparentTemperatureMinTime": 1579323600,
                "apparentTemperatureMax": 15.31,
                "apparentTemperatureMaxTime": 1579403460
            },
            {
                "time": 1579410000,
                "summary": "Windy in the afternoon.",
                "icon": "snow",
                "sunriseTime": 1579436340,
                "sunsetTime": 1579470180,
                "moonPhase": 0.84,
                "precipIntensity": 0.0024,
                "precipIntensityMax": 0.0191,
                "precipIntensityMaxTime": 1579410000,
                "precipProbability": 0.45,
                "precipType": "snow",
                "precipAccumulation": 0.88,
                "temperatureHigh": 18.58,
                "temperatureHighTime": 1579454880,
                "temperatureLow": -8.93,
                "temperatureLowTime": 1579520760,
                "apparentTemperatureHigh": 3.3,
                "apparentTemperatureHighTime": 1579453380,
                "apparentTemperatureLow": -23.44,
                "apparentTemperatureLowTime": 1579520520,
                "dewPoint": 5.16,
                "humidity": 0.65,
                "pressure": 1003.6,
                "windSpeed": 12.57,
                "windGust": 40.53,
                "windGustTime": 1579457160,
                "windBearing": 304,
                "cloudCover": 0.81,
                "uvIndex": 1,
                "uvIndexTime": 1579453200,
                "visibility": 7.284,
                "ozone": 387.2,
                "temperatureMin": 1.53,
                "temperatureMinTime": 1579496400,
                "temperatureMax": 24.88,
                "temperatureMaxTime": 1579410000,
                "apparentTemperatureMin": -13.13,
                "apparentTemperatureMinTime": 1579496400,
                "apparentTemperatureMax": 14.68,
                "apparentTemperatureMaxTime": 1579410000
            }
        ]
    },
    "flags": {
        "sources": [
            "nwspa",
            "cmc",
            "gfs",
            "hrrr",
            "icon",
            "isd",
            "madis",
            "nam",
            "sref",
            "darksky",
            "nearest-precip"
        ],
        "nearest-station": 1.678,
        "units": "us"
    },
    "offset": -5
  })
end